/**
 * Copyright 2013 Alex Jones
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * @author unclealex72
 *
 */

package uk.co.unclealex.hammers.calendar.html

import org.specs2.mutable.Specification
import uk.co.unclealex.hammers.calendar.model.GameKey
import uk.co.unclealex.hammers.calendar.model.Competition
import uk.co.unclealex.hammers.calendar.model.Location
import uk.co.unclealex.hammers.calendar.January
import uk.co.unclealex.hammers.calendar.February
import uk.co.unclealex.hammers.calendar.August
import uk.co.unclealex.hammers.calendar.May
import uk.co.unclealex.hammers.calendar.October
import uk.co.unclealex.hammers.calendar.September
import uk.co.unclealex.hammers.calendar.November
import uk.co.unclealex.hammers.calendar.April
import uk.co.unclealex.hammers.calendar.March
import uk.co.unclealex.hammers.calendar.December
import uk.co.unclealex.hammers.calendar.Instant._
/**
 *
 * @author alex
 *
 */
trait SeasonHtmlGamesScannerExpectations {

  val expectedGameUpdateCommandsFor2007 = List(
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Arsenal", 2007)), Some(September(29, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Arsenal", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Arsenal", 2007)), Some(34966)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Arsenal", 2007)), Some("file:/page/MatchReport/0,,12562~37988,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Arsenal", 2007)), Some(January(1, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Arsenal", 2007)), Some("0-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Arsenal", 2007)), Some(60102)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Arsenal", 2007)), Some("file:/page/MatchReport/0,,12562~38839,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Aston Villa", 2007)), Some(May(11, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Aston Villa", 2007)), Some("2-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Aston Villa", 2007)), Some(34969)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Aston Villa", 2007)), Some("file:/page/MatchReport/0,,12562~36759,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Aston Villa", 2007)), Some(October(6, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Aston Villa", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Aston Villa", 2007)), Some(40842)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Aston Villa", 2007)), Some("file:/page/MatchReport/0,,12562~38052,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Birmingham", 2007)), Some(February(9, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Birmingham", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Birmingham", 2007)), Some(34884)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Birmingham", 2007)), Some("file:/page/MatchReport/0,,12562~39110,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Birmingham", 2007)), Some(August(18, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Birmingham", 2007)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Birmingham", 2007)), Some(24961)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Birmingham", 2007)), Some("file:/page/MatchReport/0,,12562~38147,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Blackburn", 2007)), Some(March(15, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Blackburn", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Blackburn", 2007)), Some(34006)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Blackburn", 2007)), Some("file:/page/MatchReport/0,,12562~38286,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Blackburn", 2007)), Some(December(9, 2007) at (16, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Blackburn", 2007)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Blackburn", 2007)), Some(20870)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Blackburn", 2007)), Some("file:/page/MatchReport/0,,12562~37977,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Bolton", 2007)), Some(November(4, 2007) at (16, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Bolton", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Bolton", 2007)), Some(33867)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Bolton", 2007)), Some("file:/page/MatchReport/0,,12562~37743,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Bolton", 2007)), Some(April(12, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Bolton", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Bolton", 2007)), Some(23043)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Bolton", 2007)), Some("file:/page/MatchReport/0,,12562~38482,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Chelsea", 2007)), Some(March(1, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Chelsea", 2007)), Some("0-4")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Chelsea", 2007)), Some(34969)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Chelsea", 2007)), Some("file:/page/MatchReport/0,,12562~37177,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Chelsea", 2007)), Some(December(1, 2007) at (12, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Chelsea", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Chelsea", 2007)), Some(41830)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Chelsea", 2007)), Some("file:/page/MatchReport/0,,12562~37921,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Derby County", 2007)), Some(April(19, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Derby County", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Derby County", 2007)), Some(34612)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Derby County", 2007)), Some("file:/page/MatchReport/0,,12562~38533,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Derby County", 2007)), Some(November(10, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Derby County", 2007)), Some("5-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Derby County", 2007)), Some(32440)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Derby County", 2007)), Some("file:/page/MatchReport/0,,12562~37819,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Everton", 2007)), Some(December(15, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Everton", 2007)), Some("0-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Everton", 2007)), Some(34430)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Everton", 2007)), Some("file:/page/MatchReport/0,,12562~37301,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Everton", 2007)), Some(March(22, 2008) at (17, 15))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Everton", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Everton", 2007)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Everton", 2007)), Some("file:/page/MatchReport/0,,12562~38326,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Fulham", 2007)), Some(January(12, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Fulham", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Fulham", 2007)), Some(34947)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Fulham", 2007)), Some("file:/page/MatchReport/0,,12562~38914,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Fulham", 2007)), Some(February(23, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Fulham", 2007)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Fulham", 2007)), Some(25280)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Fulham", 2007)), Some("file:/page/MatchReport/0,,12562~38688,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Liverpool", 2007)), Some(January(30, 2008) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Liverpool", 2007)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Liverpool", 2007)), Some(34977)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Liverpool", 2007)), Some("file:/page/MatchReport/0,,12562~38551,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Liverpool", 2007)), Some(March(5, 2008) at (20, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Liverpool", 2007)), Some("0-4")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Liverpool", 2007)), Some(42954)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Liverpool", 2007)), Some("file:/page/MatchReport/0,,12562~38144,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Man Utd", 2007)), Some(December(29, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Man Utd", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Man Utd", 2007)), Some(34966)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Man Utd", 2007)), Some("file:/page/MatchReport/0,,12562~38802,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Man Utd", 2007)), Some(May(3, 2008) at (12, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Man Utd", 2007)), Some("1-4")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Man Utd", 2007)), Some(76013)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Man Utd", 2007)), Some("file:/page/MatchReport/0,,12562~37408,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Manchester City", 2007)), Some(August(11, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Manchester City", 2007)), Some("0-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Manchester City", 2007)), Some(34921)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Manchester City", 2007)), Some("file:/page/MatchReport/0,,12562~37428,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Manchester City", 2007)), Some(January(20, 2008) at (16, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Manchester City", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Manchester City", 2007)), Some(39042)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Manchester City", 2007)), Some("file:/page/MatchReport/0,,12562~38955,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Middlesbrough", 2007)), Some(September(15, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Middlesbrough", 2007)), Some("3-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Middlesbrough", 2007)), Some(34351)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Middlesbrough", 2007)), Some("file:/page/MatchReport/0,,12562~37580,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Middlesbrough", 2007)), Some(December(22, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Middlesbrough", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Middlesbrough", 2007)), Some(26007)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Middlesbrough", 2007)), Some("file:/page/MatchReport/0,,12562~38776,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Newcastle", 2007)), Some(April(26, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Newcastle", 2007)), Some("2-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Newcastle", 2007)), Some(34980)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Newcastle", 2007)), Some("file:/page/MatchReport/0,,12562~37364,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Newcastle", 2007)), Some(September(23, 2007) at (13, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Newcastle", 2007)), Some("1-3")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Newcastle", 2007)), Some(50104)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Newcastle", 2007)), Some("file:/page/MatchReport/0,,12562~37583,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Portsmouth", 2007)), Some(April(8, 2008) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Portsmouth", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Portsmouth", 2007)), Some(33629)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Portsmouth", 2007)), Some("file:/page/MatchReport/0,,12562~38445,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Portsmouth", 2007)), Some(October(27, 2007) at (17, 15))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Portsmouth", 2007)), Some("0-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Portsmouth", 2007)), Some(20525)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Portsmouth", 2007)), Some("file:/page/MatchReport/0,,12562~37696,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Reading", 2007)), Some(December(26, 2007) at (13, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Reading", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Reading", 2007)), Some(34277)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Reading", 2007)), Some("file:/page/MatchReport/0,,12562~38747,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Reading", 2007)), Some(September(1, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Reading", 2007)), Some("3-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Reading", 2007)), Some(23533)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Reading", 2007)), Some("file:/page/MatchReport/0,,12562~38214,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Sunderland", 2007)), Some(October(21, 2007) at (16, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Sunderland", 2007)), Some("3-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Sunderland", 2007)), Some(34913)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Sunderland", 2007)), Some("file:/page/MatchReport/0,,12562~38126,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Sunderland", 2007)), Some(March(29, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Sunderland", 2007)), Some("1-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Sunderland", 2007)), Some(45690)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Sunderland", 2007)), Some("file:/page/MatchReport/0,,12562~38399,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Tottenham", 2007)), Some(November(25, 2007) at (13, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Tottenham", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Tottenham", 2007)), Some(34966)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Tottenham", 2007)), Some("file:/page/MatchReport/0,,12562~37870,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Tottenham", 2007)), Some(March(9, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Tottenham", 2007)), Some("0-4")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Tottenham", 2007)), Some(36062)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Tottenham", 2007)), Some("file:/page/MatchReport/0,,12562~37233,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Wigan Athletic", 2007)), Some(August(25, 2007) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Wigan Athletic", 2007)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Wigan Athletic", 2007)), Some(33793)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.HOME, "Wigan Athletic", 2007)), Some("file:/page/MatchReport/0,,12562~37470,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Wigan Athletic", 2007)), Some(February(2, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Wigan Athletic", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Wigan Athletic", 2007)), Some(20525)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.PREM, Location.AWAY, "Wigan Athletic", 2007)), Some("file:/page/MatchReport/0,,12562~39064,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Bristol Rovers", 2007)), Some(August(28, 2007) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Bristol Rovers", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Bristol Rovers", 2007)), Some(10831)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Bristol Rovers", 2007)), Some("file:/page/MatchReport/0,,12562~42975,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Coventry City", 2007)), Some(October(30, 2007) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Coventry City", 2007)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Coventry City", 2007)), Some(23968)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.AWAY, "Coventry City", 2007)), Some("file:/page/MatchReport/0,,12562~43087,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Everton", 2007)), Some(December(12, 2007) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Everton", 2007)), Some("1-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Everton", 2007)), Some(28777)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Everton", 2007)), Some("file:/page/MatchReport/0,,12562~43165,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Plymouth", 2007)), Some(September(26, 2007) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Plymouth", 2007)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Plymouth", 2007)), Some(25774)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Plymouth", 2007)), Some("file:/page/MatchReport/0,,12562~43058,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.HOME, "Manchester City", 2007)), Some(January(5, 2008) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.HOME, "Manchester City", 2007)), Some("0-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.HOME, "Manchester City", 2007)), Some(33806)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.HOME, "Manchester City", 2007)), Some("file:/page/MatchReport/0,,12562~43214,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Manchester City", 2007)), Some(January(16, 2008) at (20, 5))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Manchester City", 2007)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Manchester City", 2007)), Some(27809)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Manchester City", 2007)), Some("file:/page/MatchReport/0,,12562~43288,00.html")))

  val expectedGameUpdateCommandsFor2011 = List(
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Aldershot Town", 2011)), Some(August(24, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Aldershot Town", 2011)), Some("1-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Aldershot Town", 2011)), Some(19879)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.LGCP, Location.HOME, "Aldershot Town", 2011)), Some("file:/page/MatchReport/0,,12562~60962,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Sheffield Wed", 2011)), Some(January(8, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Sheffield Wed", 2011)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Sheffield Wed", 2011)), Some(17916)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FACP, Location.AWAY, "Sheffield Wed", 2011)), Some("file:/page/MatchReport/0,,12562~61383,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Barnsley", 2011)), Some(December(17, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Barnsley", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Barnsley", 2011)), Some(34749)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Barnsley", 2011)), Some("file:/page/MatchReport/0,,12562~58614,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Barnsley", 2011)), Some(April(7, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Barnsley", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Barnsley", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Barnsley", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Birmingham", 2011)), Some(April(9, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Birmingham", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Birmingham", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Birmingham", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Birmingham", 2011)), Some(December(26, 2011) at (17, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Birmingham", 2011)), Some("1-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Birmingham", 2011)), Some(20214)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Birmingham", 2011)), Some("file:/page/MatchReport/0,,12562~58336,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Blackpool", 2011)), Some(October(15, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Blackpool", 2011)), Some("4-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Blackpool", 2011)), Some(31448)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Blackpool", 2011)), Some("file:/page/MatchReport/0,,12562~57649,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Blackpool", 2011)), Some(February(18, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Blackpool", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Blackpool", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Blackpool", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Brighton", 2011)), Some(April(14, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Brighton", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Brighton", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Brighton", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Brighton", 2011)), Some(October(24, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Brighton", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Brighton", 2011)), Some(20686)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Brighton", 2011)), Some("file:/page/MatchReport/0,,12562~57697,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Bristol City", 2011)), Some(November(1, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Bristol City", 2011)), Some("0-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Bristol City", 2011)), Some(27980)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Bristol City", 2011)), Some("file:/page/MatchReport/0,,12562~58215,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Bristol City", 2011)), Some(April(17, 2012) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Bristol City", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Bristol City", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Bristol City", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Burnley", 2011)), Some(December(3, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Burnley", 2011)), Some("1-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Burnley", 2011)), Some(26274)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Burnley", 2011)), Some("file:/page/MatchReport/0,,12562~58547,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Burnley", 2011)), Some(March(24, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Burnley", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Burnley", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Burnley", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Cardiff City", 2011)), Some(August(7, 2011) at (13, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Cardiff City", 2011)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Cardiff City", 2011)), Some(25680)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Cardiff City", 2011)), Some("file:/page/MatchReport/0,,12562~58440,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Cardiff City", 2011)), Some(March(4, 2012) at (13, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Cardiff City", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Cardiff City", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Cardiff City", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Coventry City", 2011)), Some(January(2, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Coventry City", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Coventry City", 2011)), Some(34936)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Coventry City", 2011)), Some("file:/page/MatchReport/0,,12562~59324,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Coventry City", 2011)), Some(November(19, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Coventry City", 2011)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Coventry City", 2011)), Some(20524)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Coventry City", 2011)), Some("file:/page/MatchReport/0,,12562~58275,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Crystal Palace", 2011)), Some(February(25, 2012) at (12, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Crystal Palace", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Crystal Palace", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Crystal Palace", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Crystal Palace", 2011)), Some(October(1, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Crystal Palace", 2011)), Some("2-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Crystal Palace", 2011)), Some(20074)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Crystal Palace", 2011)), Some("file:/page/MatchReport/0,,12562~57571,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Derby County", 2011)), Some(November(26, 2011) at (17, 20))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Derby County", 2011)), Some("3-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Derby County", 2011)), Some(27864)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Derby County", 2011)), Some("file:/page/MatchReport/0,,12562~58490,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Derby County", 2011)), Some(December(31, 2011) at (13, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Derby County", 2011)), Some("1-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Derby County", 2011)), Some(28067)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Derby County", 2011)), Some("file:/page/MatchReport/0,,12562~58385,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Doncaster", 2011)), Some(March(10, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Doncaster", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Doncaster", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Doncaster", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Doncaster", 2011)), Some(August(13, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Doncaster", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Doncaster", 2011)), Some(11344)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Doncaster", 2011)), Some("file:/page/MatchReport/0,,12562~57839,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Hull City", 2011)), Some(April(28, 2012) at (12, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Hull City", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Hull City", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Hull City", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Hull City", 2011)), Some(November(5, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Hull City", 2011)), Some("2-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Hull City", 2011)), Some(21756)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Hull City", 2011)), Some("file:/page/MatchReport/0,,12562~58231,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Ipswich Town", 2011)), Some(September(27, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Ipswich Town", 2011)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Ipswich Town", 2011)), Some(27709)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Ipswich Town", 2011)), Some("file:/page/MatchReport/0,,12562~57558,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Ipswich Town", 2011)), Some(January(31, 2012) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Ipswich Town", 2011)), Some("1-5")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Ipswich Town", 2011)), Some(22185)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Ipswich Town", 2011)), Some("file:/page/MatchReport/0,,12562~59496,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leeds United", 2011)), Some(August(21, 2011) at (13, 15))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leeds United", 2011)), Some("2-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leeds United", 2011)), Some(28252)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leeds United", 2011)), Some("file:/page/MatchReport/0,,12562~57927,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leeds United", 2011)), Some(March(17, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leeds United", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leeds United", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leeds United", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leicester City", 2011)), Some(October(29, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leicester City", 2011)), Some("3-2")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leicester City", 2011)), Some(30410)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Leicester City", 2011)), Some("file:/page/MatchReport/0,,12562~58179,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leicester City", 2011)), Some(April(21, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leicester City", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leicester City", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Leicester City", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Middlesbrough", 2011)), Some(March(20, 2012) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Middlesbrough", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Middlesbrough", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Middlesbrough", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Middlesbrough", 2011)), Some(November(29, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Middlesbrough", 2011)), Some("2-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Middlesbrough", 2011)), Some(18457)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Middlesbrough", 2011)), Some("file:/page/MatchReport/0,,12562~58520,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Millwall", 2011)), Some(February(4, 2012) at (12, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Millwall", 2011)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Millwall", 2011)), Some(27774)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Millwall", 2011)), Some("file:/page/MatchReport/0,,12562~59529,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Millwall", 2011)), Some(September(17, 2011) at (12, 30))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Millwall", 2011)), Some("0-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Millwall", 2011)), Some(16078)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Millwall", 2011)), Some("file:/page/MatchReport/0,,12562~58107,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Nottm Forest", 2011)), Some(January(21, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Nottm Forest", 2011)), Some("2-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Nottm Forest", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Nottm Forest", 2011)), Some("file:/page/MatchReport/0,,12562~59439,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Nottm Forest", 2011)), Some(August(28, 2011) at (13, 15))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Nottm Forest", 2011)), Some("4-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Nottm Forest", 2011)), Some(21379)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Nottm Forest", 2011)), Some("file:/page/MatchReport/0,,12562~57971,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Peterborough", 2011)), Some(September(24, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Peterborough", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Peterborough", 2011)), Some(29895)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Peterborough", 2011)), Some("file:/page/MatchReport/0,,12562~57522,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Peterborough", 2011)), Some(February(11, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Peterborough", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Peterborough", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Peterborough", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Portsmouth", 2011)), Some(September(10, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Portsmouth", 2011)), Some("4-3")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Portsmouth", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Portsmouth", 2011)), Some("file:/page/MatchReport/0,,12562~58042,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Portsmouth", 2011)), Some(January(14, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Portsmouth", 2011)), Some("1-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Portsmouth", 2011)), Some(18492)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Portsmouth", 2011)), Some("file:/page/MatchReport/0,,12562~59392,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Reading", 2011)), Some(March(31, 2012) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Reading", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Reading", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Reading", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Reading", 2011)), Some(December(10, 2011) at (15, 0))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Reading", 2011)), Some("0-3")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Reading", 2011)), Some(24026)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Reading", 2011)), Some("file:/page/MatchReport/0,,12562~58567,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Southampton", 2011)), Some(February(14, 2012) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Southampton", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Southampton", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Southampton", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Southampton", 2011)), Some(October(18, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Southampton", 2011)), Some("0-1")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Southampton", 2011)), Some(32152)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Southampton", 2011)), Some("file:/page/MatchReport/0,,12562~57685,00.html")),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Watford", 2011)), Some(March(7, 2012) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Watford", 2011)), None),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Watford", 2011)), None),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.HOME, "Watford", 2011)), None),
    DatePlayedUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Watford", 2011)), Some(August(16, 2011) at (19, 45))),
    ResultUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Watford", 2011)), Some("4-0")),
    AttendenceUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Watford", 2011)), Some(14747)),
    MatchReportUpdateCommand(GameKeyLocator(new GameKey(Competition.FLC, Location.AWAY, "Watford", 2011)), Some("file:/page/MatchReport/0,,12562~57881,00.html")))
}
